"""add tmdb_person_id to crew_person

Revision ID: 1b39ff3417c2
Revises: 878c2868c8fe
Create Date: 2026-03-31 08:47:17.402485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b39ff3417c2'
down_revision: Union[str, Sequence[str], None] = '878c2868c8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew_person', sa.Column('tmdb_person_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'crew_person', ['tmdb_person_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crew_person', type_='unique')
    op.drop_column('crew_person', 'tmdb_person_id')
    # ### end Alembic commands ###
