import type { MovieDetails, WatchedMovie } from "@/types/movie";

export const MOCK_USER = {
  displayName: "Movie Lover",
  email: "movielover@example.com",
  photoURL: null as string | null,
};

export const MOCK_STATS = {
  liked: 24,
  passed: 18,
  rated: 12,
};

const MOCK_LIKED_MOVIES: MovieDetails[] = [
  {
    movie_id: "1",
    tmdb_id: "155",
    title: "The Dark Knight",
    poster_url: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911BTUgMe1nNaD3.jpg",
    release_year: 2008,
    rating: 9.0,
    genres: ["Action", "Crime", "Drama"],
    is_adult: false,
    synopsis: "When the menace known as the Joker wreaks havoc on Gotham City, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    cast: [],
    trailer_url: "",
    runtime: 152,
    movie_providers: [],
  },
  {
    movie_id: "2",
    tmdb_id: "550",
    title: "Fight Club",
    poster_url: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    release_year: 1999,
    rating: 8.8,
    genres: ["Drama"],
    is_adult: false,
    synopsis: "An insomniac office worker and a devil-may-care soap maker form an underground fight club.",
    cast: [],
    trailer_url: "",
    runtime: 139,
    movie_providers: [],
  },
  {
    movie_id: "3",
    tmdb_id: "680",
    title: "Pulp Fiction",
    poster_url: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_year: 1994,
    rating: 8.9,
    genres: ["Thriller", "Crime"],
    is_adult: false,
    synopsis: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine.",
    cast: [],
    trailer_url: "",
    runtime: 154,
    movie_providers: [],
  },
  {
    movie_id: "4",
    tmdb_id: "27205",
    title: "Inception",
    poster_url: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    release_year: 2010,
    rating: 8.8,
    genres: ["Action", "Sci-Fi", "Adventure"],
    is_adult: false,
    synopsis: "A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea.",
    cast: [],
    trailer_url: "",
    runtime: 148,
    movie_providers: [],
  },
  {
    movie_id: "5",
    tmdb_id: "329865",
    title: "Arrival",
    poster_url: "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
    release_year: 2016,
    rating: 7.9,
    genres: ["Drama", "Sci-Fi"],
    is_adult: false,
    synopsis: "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
    cast: [],
    trailer_url: "",
    runtime: 116,
    movie_providers: [],
  },
  {
    movie_id: "6",
    tmdb_id: "244786",
    title: "Whiplash",
    poster_url: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedos.jpg",
    release_year: 2014,
    rating: 8.5,
    genres: ["Drama", "Music"],
    is_adult: false,
    synopsis: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    cast: [],
    trailer_url: "",
    runtime: 106,
    movie_providers: [],
  },
];

export const MOCK_WATCHED_MOVIES: WatchedMovie[] = [
  { movie: MOCK_LIKED_MOVIES[0], rating: 5, watchedAt: "2025-01-15T00:00:00Z" },
  { movie: MOCK_LIKED_MOVIES[1], rating: 4, watchedAt: "2025-01-20T00:00:00Z" },
  { movie: MOCK_LIKED_MOVIES[4], rating: 5, watchedAt: "2025-02-01T00:00:00Z" },
];

export { MOCK_LIKED_MOVIES };
